### ISSUE TITLE
Collections V2 is invalid

### ISSUE THREAD

**Issue by t-botz** [postmanlabs/schemas#12] opened 2017-07-02 02:52 UTC
https://github.com/postmanlabs/schemas/blob/develop/json/collection/v2.0.0/index.json#L856
The above line is invalid according to the json schema specs.
You can easily test your schema here : 
http://www.jsonschemavalidator.net/

**Comment by kunagpal** [comment] 2017-07-03 14:03
Duplicate of #13

**Comment by t-botz** [comment] 2017-07-03 21:55
@kunagpal how is that a duplicate?? One is about the schema itself, this one is about the data generated.... That's two very different problems with two very different resolution...

**Comment by jvkaam** [comment] 2017-07-07 11:39
+1

**Comment by kunagpal** [comment] 2017-07-11 14:18
@jvkaam @thibaultdelor This issue has been fixed, feel free to revert if you're facing other difficulties 😄

**Closed as completed by kunagpal** 2017-07-11 14:18 UTC
